#spring application configuration
spring:
  application:
    name: ticket_resell_be
  #database configuration
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://178.128.96.120:5432/ticket_resell
    url: jdbc:postgresql://localhost:5432/ticket_resell
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  #mail configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
  springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html
    operationsSorter: method
    tagsSorter: alpha
    display-request-duration: true
    disable-swagger-default-url: true
#server configuration
server:
  port: 8081
  servlet:
    context-path: /
