name: Depoly on VPS

on:
  push:
    branches:
      - main


jobs:
  docker-compose:
    runs-on: self-hosted
    environment: docker
    steps:

    - name: Checkout code
      uses: actions/checkout@v2 

    - name: Use Github Secrets
      run: |
        echo "ACCESS_TOKEN_EXP=$ACCESS_TOKEN_EXP" >> .env
        echo "DB_PASSWORD=$DB_PASSWORD" >> .env
        echo "DB_USERNAME=$DB_USERNAME" >> .env
        echo "DB_URL=$DB_URL" >> .env
        echo "GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID" >> .env
        echo "JWT_SECRET_KEY=$JWT_SECRET_KEY" >> .env
        echo "MAIL_PASSWORD=$MAIL_PASSWORD" >> .env
        echo "MAIL_USERNAME=$MAIL_USERNAME" >> .env
        echo "REFRESH_TOKEN_EXP=$REFRESH_TOKEN_EXP" >> .env
        echo "AUTHORIZATION_HEADER=$AUTHORIZATION_HEADER" >> .env
      
    - name: Run `docker compose`
      run: docker compose up --build -d